[build]
  publish = "docs/.vitepress/dist"
  command = "npx vitepress build docs"

[build.environment]
  NODE_VERSION = "18"

# 支持单页面应用路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 语言子路径重定向
[[redirects]]
  from = "/zh/*"
  to = "/zh/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200
